" -------------------------
"
" VIM FTW o/
"
" - @renatoagomes 
" - [vimrc](https://github.com/renatoagomes/dotfiles/blob/master/vim/vimrc)
"
" -------------------------

let mapleader=","
let localmapleader = "\<Space>"
set mouse=a

" plugins
source $HOME/dotfiles/vim/plugins.vimrc

" settings
source $HOME/dotfiles/vim/settings.vimrc

" functions
source $HOME/dotfiles/vim/functions.vimrc

" mappings
source $HOME/dotfiles/vim/mappings.vimrc

" workflow 
source $HOME/dotfiles/vim/workflow.vimrc

" visual 
source $HOME/dotfiles/vim/visual.vimrc

" newstuff 
source $HOME/dotfiles/vim/newstuff.vimrc

