# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/zord/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker docker-compose vi-mode)

source $ZSH/oh-my-zsh.sh
source ~/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

#####
# CUSTOM ALIASES

#conf zsh / oh-my-sh
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

# gerando ctags
alias genctags="ctags -R --exclude='.git' --exclude='node_modules' --exclude='' --exclude='public' --exclude='laradock' --exclude='*.js'"
alias art="php artisan "

#####
# PATH'S

alias ppath="cd ~/projetos/" 
alias dotpath="cd ~/dotfiles/" 
alias acordopath="cd ~/projetos/acordorapido2" 
alias ticpath="cd ~/projetos/tic-solucoes" 
alias boitatapath="cd ~/projetos/boitata" 
alias shantipath="cd ~/projetos/instituto-shanti" 


#####
# DOCKER Aliases

alias dworkspace="docker exec -it laradock_workspace_1 "
alias dart="docker exec -it laradock_workspace_1 php artisan "
alias dcomposer="docker exec -it laradock_workspace_1 composer "

alias dcreatedb='docker exec -it laradock_postgres_1 createdb  '
alias ddropdb='docker exec -it laradock_postgres_1 dropdb  '

#####
# QUICK-START ALIASES
####

#TIC
alias tic-build='ticpath && cd laradock && docker-compose up -d --build php-fpm nginx mysql phpmyadmin '
alias tic-start='ticpath && cd laradock && docker-compose up -d php-fpm nginx mysql phpmyadmin '

#AcordoRapido
alias acordo-build='acordopath && cd laradock && docker-compose up -d --build php-fpm postgres pgadmin '
alias acordo-start='acordopath && cd laradock && docker-compose up -d php-fpm nginx postgres pgadmin '

#Boitata
alias boitata-build='boitatapath && cd laradock && docker-compose up -d --build php-fpm postgres pgadmin; cd .. '
alias boitata-start='boitatapath && cd laradock && docker-compose up -d php-fpm nginx postgres pgadmin '

#shanti
alias shanti-build='shantipath && cd laradock && docker-compose up -d --build php-fpm postgres pgadmin; cd .. '
alias shanti-start='shantipath && cd laradock && docker-compose up -d php-fpm nginx postgres pgadmin '


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
