# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  # This loads NVM
source /usr/share/nvm/init-nvm.sh

# Path to your oh-my-zsh installation.
export ZSH=/home/zord/.oh-my-zsh
export PATH="$(yarn global bin):$PATH"
export PATH="/home/zord/.local/bin/:$PATH"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker docker-compose vi-mode zsh-z)

source $ZSH/oh-my-zsh.sh
source ~/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

#####
# CUSTOM ALIASES
# ####

# gerando ctags
alias genctags="ctags -R --php-kinds=cfit"
#alias genctags="ctags -R --exclude='.git' --exclude='node_modules' --exclude='public' --exclude='laradock' --exclude='*.js' --exclude='*.css' --exclude='*.scss'"

#####
# PATH'S
alias screencastpath="cd ~/screencast/" 
alias ppath="cd ~/projetos/" 
alias dotpath="cd ~/dotfiles/" 

####
## VESSEL ALIASES
alias v='./vessel '
alias vstart='v start'
alias vstop='v stop'
alias vart='v artisan '
alias vcomp='v composer '
alias vtest="./vessel exec app vendor/bin/phpunit tests"

#####
## 'QUICK-START' ALIASES

#wifi
alias ndw='nmcli device wifi '
alias ndwl='ndw list '
alias ndwc='ndw connect '

#dns
alias fixDNS='sudo sed -e "s/127.0.0.53/8.8.8.8/" -i /etc/resolv.conf'
alias fixDNSTIC='sudo sed -e "s/127.0.0.53/10.10.10.1/" -i /etc/resolv.conf'

#brightness
alias maisbrilho='echo 15 | sudo tee /sys/class/backlight/acpi_video0/brightness'
alias menosbrilho='echo 5 | sudo tee /sys/class/backlight/acpi_video0/brightness'

# todas as alavancas juntas
alias play="maisbrilho && fixDNS && sudo setxkbmap -model pc105 -layout br -variant abnt2"

#### Scaffold alias
alias scaffe="scaff exec "
alias scaffa="scaff exec php artisan "
alias scaffat="scaff exec php artisan tinker"
alias scaffamst="scaff exec php artisan migrate:status"
alias scaffc="scaff exec composer "
alias scaffn="scaff exec npm "

## php check
alias scaffpc="scaff exec vendor/bin/phpcs --error-severity=1 --warning-severity=8"

## php fix
alias scaffpf="scaff exec vendor/bin/phpcbf"

alias gitw="git whatchanged "

alias ytdl="youtube-dl \"ytsearch:"

alias l="exa --icons -lah"

alias dpsa="docker ps -a --format='''table {{.ID}}	{{.Names}}	{{.Image}}	{{.Status}}'''"

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)t
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

#so as not to be disturbed by Ctrl-S ctrl-Q in terminals:
#[[ $- == *i* ]] && stty -ixon

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export BAT_THEME="Nord"

# vi'g?
alias protocolo='phey -f uggcf://pvqnqnb.evbcergb.fc.tbi.oe/rzceb_pvqnqnb/fwevbcergb/frzsnm/rzceb_pbafhygn_cebgbpbyb.cuc/ncv/VzcevzveEryngbevb\?aeb_cebgbpbyb\=-%2PP%60E%2P3%60C%2P%23%60C-PQE.%60%60%60%0N%60%0N\&qngn_cebgbpbyb\=%2N%2P%23%40B%2P%23%24B%2PP%60E%2P0%60%60%0N%60%0N --bhgchg cebgbpbyb.cqs && cqsgbgrkg -ynlbhg cebgbpbyb.cqs cebgbpbyb.gkg && rpub "\a ##Hygvznf nghnyvmnçõrf: \a\a" && png cebgbpbyb.gkg' 

#118M p/ 5mb com resolução ruinzinha
alias videoMenor='ffmpeg -i input.mkv -vf "scale=trunc(iw/4)*2:trunc(ih/4)*2" -c:v libx265 -crf 28 '
alias gravarV='ffmpeg -f alsa -ac 1 -i pulse -f x11grab -r 30 -s 1920x1080  -i :0.0 -acodec aac -vcodec mpeg4 -preset medium -qscale:v 5 '
